/* Every public header the fork ships, which is what
 * packages/engine/runtime/build/generate-functions.mjs walks too. The `cpp/`
 * subdirectory is excluded there (isCppHelperHeader) and here, because it is
 * C++ helpers rather than the C ABI. */
#include "fpdfview.h"
#include "fpdf_annot.h"
#include "fpdf_attachment.h"
#include "fpdf_catalog.h"
#include "fpdf_dataavail.h"
#include "fpdf_doc.h"
#include "fpdf_edit.h"
#include "fpdf_ext.h"
#include "fpdf_flatten.h"
#include "fpdf_formfill.h"
#include "fpdf_fwlevent.h"
#include "fpdf_javascript.h"
#include "fpdf_jpeg.h"
#include "fpdf_png.h"
#include "fpdf_ppo.h"
#include "fpdf_progressive.h"
#include "fpdf_save.h"
#include "fpdf_searchex.h"
#include "fpdf_signature.h"
#include "fpdf_structtree.h"
#include "fpdf_sysfontinfo.h"
#include "fpdf_text.h"
#include "fpdf_thumbnail.h"
#include "fpdf_transformpage.h"
#include "epdf_action.h"
#include "epdf_font.h"
#include "epdf_form.h"
#include "epdf_pieceinfo.h"
#include "epdf_redact.h"
#include "epdf_text.h"
