// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../../../../../../index.js";

/**
 * @example
 *     {
 *         docId: "docId",
 *         layerName: "layerName",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface RemoveNamePagesRequest {
    docId: string;
    layerName: string;
    /** Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead. */
    "X-Document-Password"?: string;
    body: CloudPDF.DocPagesRemoveNameRequest;
}
