// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  'list-all': 'List All',
  list: 'List',
  create: 'Create',
  update: 'Update',
  delete: 'Delete',
  'export-appearance': 'Export Appearance',
  flatten: 'Flatten',
};
