//! Raw bindings to the EmbedPDF PDFium fork's C ABI, generated by bindgen over
//! the same headers packages/engine/runtime/build/generate-functions.mjs walks,
//! with the same FPDF|EPDF|FORM|PDFiumExt_ filter.
//!
//! This crate is INTERNAL to the scaffold. Nothing reaches it from Swift,
//! Kotlin, Node or the browser: recommendation 3 of
//! docs/research/pdfium-rust-wrapper-decision.md prices a per-call host boundary
//! at 2.6x (wasm) to 7.16x (native) against a per-operation one, so exposing
//! this surface would be building the expensive thing on purpose.
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
