/**
 * Zod-backed engine HTTP wire entrypoint.
 *
 * Cloud transports and server routes import this subpath when they need
 * runtime validation. Local/browser runtime code should use `/runtime`.
 */

export {
  DocumentMetadataSchema,
  MetadataPatchSchema,
  MetadataUpdateResultSchema,
  AccessRequestSchema,
  AccessResponseSchema,
  OpenDocumentResponseSchema,
  DocumentHeadSchema,
  DocumentSecurityStateSchema,
  PdfSaveModeSchema,
  DocumentManifestSchema,
  ManifestPageSchema,
  CachePinsSchema,
  LayerScopesSchema,
  CacheDeltaSchema,
  MutationMetaSchema,
  EngineErrorPayloadSchema,
  PageStateSchema,
  AnnotationListPageSnapshotSchema,
  AnnotationListSnapshotAllPagesSchema,
  PageTextSnapshotSchema,
  PageGeometrySnapshotSchema,
  PageNetworkRenderFormatSchema,
  PageRenderQuerySchema,
  PageRenderAnnotatedQuerySchema,
  AnnotationAppearancesQuerySchema,
  AnnotationAppearanceManifestSchema,
  RefetchReasonSchema,
  AnnotationListMutationMetaSchema,
  AnnotationCreateResultSchema,
  AppearanceOutcomeSchema,
  AnnotationUpdateResultSchema,
  AnnotationDeleteResultSchema,
  AnnotationMoveResultSchema,
  FormSetValueResultSchema,
  FormImportResultSchema,
  FormRepairResultSchema,
  FormFieldCreateResultSchema,
  FormFieldUpdateResultSchema,
  FormFieldDeleteResultSchema,
  FormWidgetLinkResultSchema,
  PageListSnapshotSchema,
  PageLayoutSchema,
  PageBoxesSchema,
  PageMoveInputSchema,
  PageMoveResultSchema,
  AnnotationFlattenInputSchema,
  AnnotationFlattenResultSchema,
  AnnotationAppearanceExportInputSchema,
  NamedPageEntrySchema,
  PageNameInputSchema,
  PageNameResultSchema,
  PageRemoveNameInputSchema,
  PageStructureCacheSchema,
  PageRotateInputSchema,
  PageRotateResultSchema,
  PageDeleteInputSchema,
  PageDeleteResultSchema,
  PageInsertInputSchema,
  PageInsertBlankInputSchema,
  PageExtractInputSchema,
  PageInsertResultSchema,
  FormEffectSchema,
  FormEffectsResultSchema,
  PageFlattenInputSchema,
  PageFlattenResultSchema,
  RedactionApplyScopeSchema,
  RedactionApplyResultSchema,
  WeakAnnotationSessionResponseSchema,
  WeakAnnotationSessionPagesRequestSchema,
  SearchQuerySchema,
  SearchModeSchema,
  SearchRequestSchema,
  SearchSnippetSchema,
  SearchMatchSchema,
  SearchSliceSchema,
} from './wire/schemas';
export {
  PdfActionTypeSchema,
  PdfActionNodeSchema,
  PdfActionTargetRefSchema,
  PdfActionTreeSchema,
  PdfFieldActionsSchema,
  PdfPageActionsSchema,
  PdfAnnotationActionsSchema,
  DocumentActionsSnapshotSchema,
  PdfActionWireComponents,
} from './dto/PdfAction.schema';
export type {
  OpenDocumentResponse,
  AccessRequest,
  AccessResponse,
  RenderPolicy,
  DocumentHead,
  DocumentManifest,
  ManifestPage,
  LayerScopes,
  LayerScopePlane,
  CacheDelta,
  MutationMeta,
  WeakAnnotationSessionResponse,
  WeakAnnotationSessionPagesRequest,
} from './wire/schemas';
export {
  FormFieldRefSchema,
  FormWidgetRefSchema,
  FormFieldFlagsSchema,
  ToggleFieldWidgetSchema,
  FormFieldOptionSchema,
  FormFieldDTOSchema,
  FormKindSchema,
  FormSnapshotSchema,
  FormFieldValueSchema,
  FormDataFormatSchema,
  WidgetAppearanceSchema,
  WidgetPlacementSchema,
  FormFieldOptionInputSchema,
  FormFieldDraftSchema,
  FormFieldPatchSchema,
  FormValueEntrySchema,
} from './forms/schema';
export {
  FormSubmissionEntrySchema,
  FormSubmissionRequestSchema,
  FormSubmissionReceiptSchema,
} from './forms/submission';
export { DEFAULT_LAYER_NAME, wirePaths, wireTemplates } from './wire/paths';
// General resource catalog + route-guard helper (server uses this for
// every read endpoint, not just CDN-cacheable ones).
export { checkResourceAccess, DOC_RESOURCES } from './wire/resources';
export type {
  CapabilityRequirement,
  DocResourceDescriptor,
  DocResourceId,
  RouteKind,
} from './wire/resources';

// CDN-shaped surface — coverage enumeration + per-request URL
// application. Scoped under wire/cdn/ so the boundary stays loud (see
// wire/cdn/index.ts for the contract). Re-exported here for ergonomic
// imports from `@embedpdf/engine-core/wire`; consumers wanting the
// narrower import path can use `@embedpdf/engine-core/wire/cdn`
// directly when that entry is published.
export { applyCdnAccess, cdnCoverageForScope, resolveResourceIdForPath } from './wire/cdn';
export type {
  ApplyCdnAccessInput,
  ApplyCdnAccessResult,
  CdnAccessInfoForApply,
  CdnCoverageEntry,
} from './wire/cdn';
export { decodeToken, encodeToken } from './wire/token';
export type { TokenInput, TokenQuery, TokenScalar, TokenSchema } from './wire/token';
export {
  AnnotationAppearancesRenderTokenSchema,
  AnnotationTokenSchema,
  ActionsTokenSchema,
  ContentTokenSchema,
  DocTokenSchema,
  LayoutTokenSchema,
  MetadataTokenSchema,
  RenderTokenSchema,
  SearchTokenSchema,
} from './wire/tokenSchemas';
export {
  decodeAnnotationAppearancesRenderToken,
  decodeAnnotationToken,
  decodeAnnotationsAllToken,
  decodeActionsToken,
  decodeAttachmentsToken,
  decodeContentToken,
  decodeDocToken,
  decodeDownloadToken,
  decodeLayoutToken,
  decodeMetadataToken,
  decodeRenderToken,
  encodeAnnotationAppearancesRenderToken,
  encodeAnnotationToken,
  encodeAnnotationsAllToken,
  encodeActionsToken,
  encodeAttachmentsToken,
  encodeContentToken,
  encodeDocToken,
  encodeDownloadToken,
  encodeLayoutToken,
  encodeMetadataToken,
  encodeRenderToken,
  encodeSearchToken,
  decodeSearchToken,
  encodeTokenText,
  decodeTokenText,
  SEARCH_RESULT_FORMAT,
} from './wire/tokens';
export type { DownloadToken, SearchToken } from './wire/tokens';
export { flatten, unflatten } from './wire/flatten';
export type { WireFlat, WireScalar } from './wire/flatten';
export {
  annotationAppearancesImageOptionsToToken,
  annotationAppearancesImageOptionsToWire,
  annotationRenderOptionsFromImageOptions,
  pageRenderOptionsFromImageOptions,
  renderImageOptionsToToken,
  renderImageOptionsToWire,
} from './wire/renderOptionsCodec';
export type { AnnotationRenderVersion, RenderVersions } from './wire/renderOptionsCodec';

// Canonical PDF-document geometry schemas (zod). Exported from `wire` ONLY.
export {
  PdfPointSchema,
  PdfRectSchema,
  PdfSizeSchema,
  PdfQuadSchema,
  PdfRotationSchema,
  LinePointsSchema,
  InkListSchema,
  CalloutLineSchema,
} from './geometry/schemas';

export {
  AnnotationStableIdSchema,
  AnnotationRefSchema,
  RevisionTokenSchema,
  AnnotationFlagsSchema,
  AnnotationFlagsPartialSchema,
  ColorSchema,
  PointSchema,
  RectSchema,
  LineEndingSchema,
  LineEndingsSchema,
  AnnotationBorderStyleSchema,
  PdfRectDifferencesSchema,
  StandardFontSchema,
  TextAlignmentSchema,
  FreeTextIntentSchema,
  CaretIntentSchema,
  StrikeoutIntentSchema,
  InkIntentSchema,
  BlendModeSchema,
  AnnotationBaseShape,
  AnnotationDraftBaseShape,
  AnnotationPatchBaseShape,
} from './annotation/base.schema';

export {
  ANNOTATION_KINDS,
  KIND_BY_SUBTYPE,
  AnnotationDTOSchema,
  AnnotationDraftSchema,
  AnnotationPatchSchema,
  HighlightDTOSchema,
  HighlightDraftSchema,
  HighlightPatchSchema,
  UnderlineDTOSchema,
  UnderlineDraftSchema,
  UnderlinePatchSchema,
  SquigglyDTOSchema,
  SquigglyDraftSchema,
  SquigglyPatchSchema,
  StrikeoutDTOSchema,
  StrikeoutDraftSchema,
  StrikeoutPatchSchema,
  CircleDTOSchema,
  CircleDraftSchema,
  CirclePatchSchema,
  SquareDTOSchema,
  SquareDraftSchema,
  SquarePatchSchema,
  PolygonDTOSchema,
  PolygonDraftSchema,
  PolygonPatchSchema,
  PolylineDTOSchema,
  PolylineDraftSchema,
  PolylinePatchSchema,
  LineDTOSchema,
  LineDraftSchema,
  LinePatchSchema,
  LinkDTOSchema,
  LinkDraftSchema,
  LinkPatchSchema,
  PdfDestinationSchema,
  PdfLinkTargetSchema,
  PdfLinkTargetWritableSchema,
  InkDTOSchema,
  InkDraftSchema,
  InkPatchSchema,
  FreeTextDTOSchema,
  FreeTextDraftSchema,
  FreeTextPatchSchema,
  CaretDTOSchema,
  CaretDraftSchema,
  CaretPatchSchema,
  TextDTOSchema,
  TextDraftSchema,
  TextPatchSchema,
  NoteIconSchema,
  StampDTOSchema,
  StampWireDraftSchema,
  StampWirePatchSchema,
  ResourceRefSchema,
  FileAttachmentDTOSchema,
  FileAttachmentWireDraftSchema,
  FileAttachmentPatchSchema,
  FileAttachmentIconSchema,
  WireAttachmentFileSchema,
  UnsupportedDTOSchema,
  UnsupportedDraftSchema,
  UnsupportedPatchSchema,
} from './annotation/kinds';
export {
  AttachmentFileInfoSchema,
  EmbeddedFileItemSchema,
  EmbeddedFileRefSchema,
} from './dto/Attachment.schema';
export {
  AttachmentsCacheSchema,
  AttachmentCreateResultSchema,
  AttachmentDeleteResultSchema,
} from './wire/schemas';
