// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  delete: 'Delete',
  extract: 'Extract',
  flatten: 'Flatten',
  insert: 'Insert',
  'insert-blank': 'Insert Blank',
  move: 'Move',
  'set-name': 'Set Name',
  'remove-name': 'Remove Name',
  rotate: 'Rotate',
};
