// This file was auto-generated by Fern from our API Definition.

export interface DocPagesRemoveName400Response {
    name: DocPagesRemoveName400Response.Name;
    code: DocPagesRemoveName400Response.Code;
    message: string;
    details?: Record<string, unknown> | undefined;
}

export namespace DocPagesRemoveName400Response {
    export const Name = {
        EngineError: "EngineError",
    } as const;
    export type Name = (typeof Name)[keyof typeof Name];
    export const Code = {
        Unknown: "Unknown",
        InvalidArg: "InvalidArg",
        DocNotOpen: "DocNotOpen",
        DocOpenFailed: "DocOpenFailed",
        DocPasswordRequired: "DocPasswordRequired",
        DocPasswordIncorrect: "DocPasswordIncorrect",
        SharePasswordRequired: "SharePasswordRequired",
        Aborted: "Aborted",
        Network: "Network",
        Unauthenticated: "Unauthenticated",
        Forbidden: "Forbidden",
        NotFound: "NotFound",
        WireFormat: "WireFormat",
        RuntimeUnavailable: "RuntimeUnavailable",
        InvalidReference: "InvalidReference",
        WeakAnnotationSessionConflict: "WeakAnnotationSessionConflict",
        LayerVersionConflict: "LayerVersionConflict",
        NotImplemented: "NotImplemented",
        MalformedPdf: "MalformedPdf",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
