// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocPagesRemoveName200Response {
    meta: DocPagesRemoveName200Response.Meta;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace DocPagesRemoveName200Response {
    export interface Meta {
        affectedPages: Meta.AffectedPages.Item[];
        cacheDelta: Meta.CacheDelta | null;
    }

    export namespace Meta {
        export type AffectedPages = AffectedPages.Item[];

        export namespace AffectedPages {
            export interface Item {
                pageObjectNumber: number;
                revision: Item.Revision;
                weakAnnotationState: CloudPDF.DocPagesRemoveName200ResponseMetaAffectedPagesItemWeakAnnotationState;
            }

            export namespace Item {
                export interface Revision {
                    docSessionId: string;
                    pageObjectNumber: number;
                    generation: number;
                }
            }
        }

        export interface CacheDelta {
            previousDocVersion: number;
            docVersion: number;
            annotationsVersion?: number | undefined;
            pages: CacheDelta.Pages.Item[];
        }

        export namespace CacheDelta {
            export type Pages = Pages.Item[];

            export namespace Pages {
                export interface Item {
                    pageObjectNumber: number;
                    cache: Item.Cache;
                }

                export namespace Item {
                    export interface Cache {
                        contentVersion: number;
                        annotationVersion: number;
                    }
                }
            }
        }
    }
}
