// This file was auto-generated by Fern from our API Definition.

import * as CloudPDF from "../../../src/api/index";
import { CloudPDFClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AnnotationsClient", () => {
    test("listAll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            pages: [
                {
                    pageState: {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                    annotations: [
                        {
                            subtype: "highlight",
                            ref: { kind: "objectNumber", pageObjectNumber: 1, annotObjectNumber: 1 },
                            pageObjectNumber: 1,
                            index: 1,
                            identityQuality: "durable",
                            nm: null,
                            flags: {
                                invisible: true,
                                hidden: true,
                                print: true,
                                noZoom: true,
                                noRotate: true,
                                noView: true,
                                readOnly: true,
                                locked: true,
                                toggleNoView: true,
                                lockedContents: true,
                            },
                            rect: { left: 1.1, bottom: 1.1, right: 1.1, top: 1.1 },
                            contents: null,
                            subject: null,
                            author: null,
                            created: null,
                            modified: null,
                            blendMode: "normal",
                            inReplyTo: null,
                            replyType: null,
                            color: { r: 1, g: 1, b: 1 },
                            opacity: 1.1,
                            quadPoints: [
                                {
                                    p1: { x: 1.1, y: 1.1 },
                                    p2: { x: 1.1, y: 1.1 },
                                    p3: { x: 1.1, y: 1.1 },
                                    p4: { x: 1.1, y: 1.1 },
                                },
                            ],
                        },
                    ],
                },
            ],
            auditHead: 1,
        };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/annotations/items")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.annotations.listAll({
            docId: "docId",
            layerName: "layerName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/annotations/items")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.listAll({
                docId: "docId",
                layerName: "layerName",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("listAll (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/annotations/items")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.listAll({
                docId: "docId",
                layerName: "layerName",
            });
        }).rejects.toThrow(CloudPDF.ConflictError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            pageState: {
                pageObjectNumber: 1,
                revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                weakAnnotationState: { kind: "unknown" },
            },
            annotations: [
                {
                    subtype: "highlight",
                    ref: { kind: "objectNumber", pageObjectNumber: 1, annotObjectNumber: 1 },
                    pageObjectNumber: 1,
                    index: 1,
                    identityQuality: "durable",
                    nm: "nm",
                    flags: {
                        invisible: true,
                        hidden: true,
                        print: true,
                        noZoom: true,
                        noRotate: true,
                        noView: true,
                        readOnly: true,
                        locked: true,
                        toggleNoView: true,
                        lockedContents: true,
                    },
                    rect: { left: 1.1, bottom: 1.1, right: 1.1, top: 1.1 },
                    contents: "contents",
                    subject: "subject",
                    author: "author",
                    created: "2024-01-15T09:30:00Z",
                    modified: "2024-01-15T09:30:00Z",
                    blendMode: "normal",
                    inReplyTo: { kind: "objectNumber", pageObjectNumber: 1, annotObjectNumber: 1 },
                    replyType: "reply",
                    userId: "userId",
                    groupId: "groupId",
                    createdBy: "createdBy",
                    updatedBy: "updatedBy",
                    color: { r: 1, g: 1, b: 1 },
                    opacity: 1.1,
                    quadPoints: [
                        {
                            p1: { x: 1.1, y: 1.1 },
                            p2: { x: 1.1, y: 1.1 },
                            p3: { x: 1.1, y: 1.1 },
                            p4: { x: 1.1, y: 1.1 },
                        },
                    ],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/annotations/pages/1/items")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.annotations.list({
            docId: "docId",
            layerName: "layerName",
            pon: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/annotations/pages/1/items")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.list({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/annotations/pages/1/items")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.annotations.create({
            docId: "docId",
            layerName: "layerName",
            pon: 1,
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/annotations/pages/1/items")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.create({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/annotations/pages/1/items")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.create({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .delete("/v1/docs/docId/layers/layerName/annotations/pages/1/items/annotKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.annotations.delete({
            docId: "docId",
            layerName: "layerName",
            pon: 1,
            annotKey: "annotKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/docs/docId/layers/layerName/annotations/pages/1/items/annotKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.delete({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                annotKey: "annotKey",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/docs/docId/layers/layerName/annotations/pages/1/items/annotKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.annotations.update({
            docId: "docId",
            layerName: "layerName",
            pon: 1,
            annotKey: "annotKey",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/docs/docId/layers/layerName/annotations/pages/1/items/annotKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.update({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                annotKey: "annotKey",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/docs/docId/layers/layerName/annotations/pages/1/items/annotKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.update({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                annotKey: "annotKey",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("flatten (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/annotations/pages/1/items/flatten")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.annotations.flatten({
            docId: "docId",
            layerName: "layerName",
            pon: 1,
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("flatten (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/annotations/pages/1/items/flatten")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.flatten({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("flatten (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/annotations/pages/1/items/flatten")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.annotations.flatten({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });
});
