// This file was auto-generated by Fern from our API Definition.

import * as CloudPDF from "../../../src/api/index";
import { CloudPDFClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("PagesClient", () => {
    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.delete({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.delete({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.delete({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("flatten (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/flatten")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.flatten({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("flatten (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/flatten")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.flatten({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("flatten (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/flatten")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.flatten({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("insertBlank (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/insert-blank")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.insertBlank({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("insertBlank (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/insert-blank")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.insertBlank({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("insertBlank (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/insert-blank")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.insertBlank({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("move (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/move")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.move({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("move (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/move")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.move({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("move (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/move")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.move({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("setName (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/names")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.setName({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("setName (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/names")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.setName({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("setName (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/names")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.setName({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("removeName (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/names/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.removeName({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeName (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/names/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.removeName({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("removeName (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/names/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.removeName({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("rotate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    annotationsVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.pages.rotate({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("rotate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.rotate({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("rotate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/pages/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.pages.rotate({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });
});
